name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x
        
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 2.1.x
        
    # .NET Frameworks are preinstalled
                
    - name: Build Debug
      working-directory: ./src
      run: dotnet build --configuration Debug
      
    - name: Build Release
      working-directory: ./src
      run: dotnet build --configuration Release
      
    - name: Test
      working-directory: ./test
      run: dotnet test --verbosity normal
